// MainViewModel
import "Framework/ViewModelBase.idl";
import "Framework/DelegateCommand.idl";

namespace MvvmCppWinRT
{
	unsealed runtimeclass MainViewModel : ViewModelBase
    {
        MainViewModel();
		String Title{ get; set; };
		Double TextSize{ get; };
		DelegateCommand OnClickCommand{ get; };
	}
}
