// MainViewModel
import "Framework/BindableBase.idl";
import "Framework/DelegateCommand.idl";

namespace MvvmCppWinRT
{
	[default_interface]
	unsealed runtimeclass MainViewModel : MvvmCppWinRT.BindableBase
    {
        MainViewModel();
		String Title{ get; set; };
		Double TextSize{ get; };
		Windows.UI.Xaml.Input.ICommand OnClickCommand{ get; };
	}
}
