// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/impl/Windows.UI.Xaml.Data.1.h"
#include "winrt/impl/Windows.UI.Xaml.1.h"
#include "winrt/impl/Windows.UI.Xaml.Input.1.h"
#include "winrt/impl/Framework.1.h"

WINRT_EXPORT namespace winrt::Framework {

}

namespace winrt::impl {

}

WINRT_EXPORT namespace winrt::Framework {

struct WINRT_EBO BindableBase :
    Framework::IBindableBaseProtected,
    impl::base<BindableBase, Windows::UI::Xaml::DependencyObject>,
    impl::require<BindableBase, Windows::UI::Xaml::Data::INotifyPropertyChanged, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2>
{
    BindableBase(std::nullptr_t) noexcept {}
    BindableBase();
};

struct WINRT_EBO DelegateCommand :
    Framework::IDelegateCommand,
    impl::base<DelegateCommand, Windows::UI::Xaml::DependencyObject>,
    impl::require<DelegateCommand, Windows::UI::Xaml::IDependencyObject, Windows::UI::Xaml::IDependencyObject2, Windows::UI::Xaml::Input::ICommand>
{
    DelegateCommand(std::nullptr_t) noexcept {}
};

}
