// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/impl/Windows.UI.Xaml.Data.0.h"
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Windows.UI.Xaml.Input.0.h"
#include "winrt/impl/Framework.0.h"

WINRT_EXPORT namespace winrt::Framework {

struct WINRT_EBO IBindableBaseFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBindableBaseFactory>
{
    IBindableBaseFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IBindableBaseProtected :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBindableBaseProtected>
{
    IBindableBaseProtected(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IDelegateCommand :
    Windows::Foundation::IInspectable,
    impl::consume_t<IDelegateCommand>
{
    IDelegateCommand(std::nullptr_t = nullptr) noexcept {}
};

}
