namespace Framework
{
	unsealed runtimeclass BindableBase : Windows.UI.Xaml.DependencyObject, Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		BindableBase();
		protected void RaisePropertyChanged(String propertyName);
	}
}
